version: '3.3'

services:
  my-db:
    image: mysql:5.7.16
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'helder'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1234'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1234'
      # Where our data will be persisted
    ports:
      - "3306:3306"
    volumes:
      - ./bdd:/var/lib/mysql
    networks:
      - backend  
  
  
  app:
    image: care_and_park_api_docker:latest
    depends_on: 
      - my-db 
    ports:
      - "8080:8080"
    networks:
      - backend  
volumes:
  db:

networks:
  backend: