version: '3.3'

services:
  db:
    image: mysql:5.7.16
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'helder'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1234'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1234'
      # Where our data will be persisted
    volumes:
      - ./bdd/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 3306:80
    environment:
      - PMA_ARBITRARY=1
# Names our volume
volumes:
  my-db: